### ISSUE TITLE
Sharing erroring out for private Shipment object

### ISSUE THREAD

**Issue by njhop** [mshanemc/LightningSharing#20]
This was previously working, but now when I try to share the standard Shipment object, i get 2 error messages:

"An internal server error has occurred Error ID: 467507303-285 (1132927942)
Sharing Settings must be private or public read/write to enable manual sharing"

When I click share again after the initial failure, it takes me to the sharing screen, but when I select to add permissions to someone:

"There is no sharing table for that object. Are you SURE you changed the sharing setting to PRIVATE or READ ?"

I'm positive the sharing for Shipments is Private. I've checked about 5 times. Do you know what might be happening here? I'm on version 1.9.

**Comment by mshanemc** [comment]
Hey...I'm not a FSL expert, but I'm pretty sure that shipments can't be shared.  There's not, for example, a ShipmentShare table anywhere.

Also doesn't support criteria-based sharing rules
https://help.salesforce.com/articleView?id=security_about_sharing_rules.htm&type=5
