### ISSUE TITLE
support for communities

### ISSUE THREAD

**Issue by gianlucatomat** [mshanemc/LightningSharing#23]
Hi, it seems like support to lightning:navigation has come for communities as well:

https://developer.salesforce.com/docs/component-library/bundle/lightning:navigation/documentation

Would it be possible to add this support?

**Comment by mshanemc** [comment]
the LightningComponent page type isn't support in communities (navigates to a component without having to put it on a package).

You **might** be able to just put this component inside a wrapper that can go on a communities page and then navigate to that with a button (button would need to pass in the attributes to your wrapper, which would pass them down to the component).

This isn't a top priority for me...any chance you'd be able to give it a try?  If it works, we could include the communities wrapper and doc the button solution.

**Comment by mshanemc** [comment]
done, in v1.13, but in a slightly different way than lightning:navigation.  

See docs for install link and explanation
