### ISSUE TITLE
User should have the ability to return to the previous menu on mobile verssion

### ISSUE THREAD

**Issue by acx-aleksandr-apanasenkov** [mshanemc/LightningSharing#25]
If the user stays on the Contact record and clicks on the "Sharing" button, he can't return to the previous menu. There is neither special button nor swiping function.
![image](https://user-images.githubusercontent.com/51746720/61622495-9445c280-ac7d-11e9-8645-8c8382799793.png)

**Comment by mshanemc** [comment]
what version are you seeing this on?  In the Salesforce Mobile app?

And that back arrow in the top left doesn't work?

It looks like the entire lightning-card is missing from this screenshot

**Comment by acx-aleksandr-apanasenkov** [comment]
@mshanemc ,
The previous screenshot was taken from a computer. This time I'm using the Salesforce Mobile app. There is no possibility to return to the previous page.
![image](https://user-images.githubusercontent.com/51746720/61692830-0a5a3000-ad37-11e9-9249-4884e698ba81.png)

**Comment by mshanemc** [comment]
This seems like it will work in the new version of the mobile app, available in winter20.

![UNADJUSTEDNONRAW_thumb_2d0e](https://user-images.githubusercontent.com/4261788/62882791-3fcfb900-bcf8-11e9-9e69-1663bbcc6baf.jpg)
