### ISSUE TITLE
Doesn't work with MDF Objects

### ISSUE THREAD

**Issue by cherman017** [mshanemc/LightningSharing#33]
Hi Shane,
Thanks again for your work here.
I created the "Doesn't Work with Price Books" issue, and you said that the problem there was that the Pricebook2 sharing was not accessible via apex or rest API.
I am now running into a similar problem with "MDF Objects" (particularly Partner Marketing Budget and Partner Fund Allocation, although I may use it with Partner Fund Request and Partner Fund Claim as well). However, it seems those objects _do_ have share tables accessible (at least, they are visible through workbench.developerforce.com).
I have set the Org-Wide Defaults to Private (screenshot below).
However, when I try to share a Partner Marketing Budget record with another user I get the error message, "Sharing Settings must be private or public read/write to enable manual sharing" (second screenshot below).
I may have configured something incorrectly though I don't believe that is the case. Do you have any thoughts or advice here?
Thanks!
-Carl

![image](https://user-images.githubusercontent.com/59401831/73797568-47cb5b80-4765-11ea-9900-6eeed05a17e8.png)

![image](https://user-images.githubusercontent.com/59401831/73797742-ae507980-4765-11ea-8611-1296536a94c4.png)

**Comment by mshanemc** [comment]
Now this I can fix.  Short explanation..the apex class was still on v38 (3 years ago!).  So it wasn't able to find tables on newer objects that didn't exist in that release.  Just bumping up the version fixed it.

What's the best way to get this fixed for you?  New packageVersion is 04t4p000001sjw2AAA.

**Comment by cherman017** [comment]
Hi Shane, thanks! I'll just install it using
https://login.salesforce.com/?ec=302&startURL=%2Fpackaging%2FinstallPackage.apexp%3Fp0%3D04t4p000001sjw2AAA%26isdtp%3Dp1
or a sandbox variation of that link.
I'll let you know how it goes.
Thanks!
-Carl

**Comment by cherman017** [comment]
Hi Shane,
Yep, that did the trick. It's working as expected with version 1.14.
Thanks!
-Carl
