### ISSUE TITLE
Package code not upgraded with sharing issue

### ISSUE THREAD

**Issue by kasimbadami** [mshanemc/LightningSharing#4]
Sub-ordinates record cannot be shared by Manager, though this code is updated on GitHub but this code is not included in package upgrade 1.6.

Also, if large amount of user records returned by search result the page becomes unresponsive. In my case the search result is of approx 300 users.

Thanks

**Comment by mshanemc** [comment]
query size...I put a 500 record limit in it.  If that's still bogging things down, maybe change it to 200?

I'll take a look at the other thing and release a new version.

**Comment by kasimbadami** [comment]
200 also makes the page down for sometimes..  can we put an search button
the search operation would only performed when clicked on button..
when would the new package would release..at least with sharing with
subordinate.

thanks

**Comment by mshanemc** [comment]
released just now.  Left it at 200, no button.

**Comment by kasimbadami** [comment]
sharing with subordinate issue.the updated code  it is already by someone
just not in package.

thanks
