### ISSUE TITLE
Receiving Null Pointer Exception for Order Sharing

### ISSUE THREAD

**Issue by Amit-Shingavi** [mshanemc/LightningSharing#42]
![NullPointer](https://user-images.githubusercontent.com/7021443/87711228-9e34cf80-c7c4-11ea-852e-04cd2fa77897.png)

**Resolution -** 
Order object is missing in isStandard(String sobj ) method in [LightningSharing](https://github.com/Amit-Shingavi/LightningSharing/blob/master/force-app/main/default/classes/LightningSharing.cls) class (Line No 297).

**Comment by mshanemc** [comment]
fascinating--Order isn't listed in the "standard" sharing tables, but has the ObjectnameId and ObjectnameAccessLevel like a "standard" sharing object.

Gotta love platform quirks.

Fix in progress.

**Comment by mshanemc** [comment]
fixed in 1.15 https://login.salesforce.com/packaging/installPackage.apexp?p0=04t4p000002BZuxAAG

**Comment by Amit-Shingavi** [comment]
Thanks Shane for the quick turn around and releasing a new major version, Appreciate it.
