### ISSUE TITLE
Sharing record of user under owner role-hierarchy

### ISSUE THREAD

**Issue by kasimbadami** [mshanemc/LightningSharing#5]
Hello Shane,
Could upgrade the package with below committed code
https://github.com/mshanemc/LightningSharing/commit/925d3f7e48194ea7c1beae2b29ea877c8b29f75f

This allows people who are above the Owner in the role-hierarchy to share records. Currently only owner and user having Modify All (System Permission) can share the record.

Thanks

**Comment by mshanemc** [comment]
this got in, right?  I'm going to publish the Summer18 version of the package next Monday after my packaging org gets upgraded.

**Comment by kasimbadami** [comment]
thanks
