### ISSUE TITLE
Clicking on a user or group under NAME column in the 1st tab fails with error

### ISSUE THREAD

**Issue by npic** [mshanemc/LightningSharing#8]
Steps to reproduce:

1. Click on the "Sharing" button on a page layout
2. In the 1st tab "View/Edit Current Permissions" click on any User or Group link under the "NAME" column
3. An error message appears: "Uncaught Unable to find action 'selectRecord' on the controller of ltngsharing:LightningSharing"

Expected behavior:

I'd expect the link would take me to the User or Group page, like in Classic.

![image](https://user-images.githubusercontent.com/566100/47285447-a1048f80-d5f3-11e8-8c30-eede8080b873.png)

**Comment by RenGro** [comment]
I can confirm the issue in different org. Would be nice to get a quick fix

**Comment by gauravbiblani** [comment]
@mshanemc This is still not resolved , it doesn't opens the Groups / Roles -- This takes care only for the Users.

**Comment by npic** [comment]
@mshanemc Thank you very much! Users do work like a charm now!

Unfortunately, I can confirm it doesn't work for Groups. Salesforce shows empty page with "You can't view this item in Lightning Experience" message and a link to open it in Classic (and it doesn't work too - "Insufficient privileges"). It could be a platform bug though - I see group ID in URL and it's resolved correctly. Please advise. Thanks!

**Comment by npic** [comment]
P.S. and yes, I'm checking it as System Admin, so I'm sure I do have sufficient privileges. I can access that Group through Setup just fine.

**Comment by acx-aleksandr-apanasenkov** [comment]
@mshanemc, I can reproduce this error on my organization. 
Steps to reproduce:
1. Navigate to the 'Contacts' tab
2. Tap on the 'Sharing' button
3.In the 1st tab "View/Edit Current Permissions" click on any User or Group link under the "NAME" column
![image](https://user-images.githubusercontent.com/51746720/61631448-0ffe3a00-ac93-11e9-80c7-a071d74f0f3a.png)
